# MAIN
title:               Jekyll-Foundation5-Starter-Kit
# description:         Jekyll-Foundation5-Starter-Kit description
url:                 http://localhost:3000
paginate:            1
baseurl:             /
source:             source
destination:        build
environment:        development

# ABOUT / CONTACT
author:
  name:              S1SYPHOS
  email:             hello@daktylos.net

# MISC
version:             1.0.0
github:
  repo:              https://github.com/S1SYPHOS/Jekyll-Foundation5-Starter-Kit
